# Generated by Django 2.1.8 on 2020-07-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=80, verbose_name='Street Address')),
                ('suburb', models.CharField(max_length=80, verbose_name='Suburb Address')),
                ('postal_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('state', models.CharField(max_length=50, verbose_name='State Name')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, null=True, unique=True, verbose_name='Last Name')),
                ('contact_name', models.CharField(max_length=50, null=True, verbose_name='Contact Name')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='python_test.Address')),
            ],
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['suburb'], name='suburb_idx'),
        ),
    ]
