# Generated by Django 2.1.8 on 2020-07-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=12, null=True, verbose_name='ZIP / Postal code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=50, null=True, verbose_name='State Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=80, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='suburb',
            field=models.CharField(max_length=80, null=True, verbose_name='Suburb Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Client Name'),
        ),
    ]
